"use strict";
const assert=require('node:assert/strict');
module.exports=async function({evaluate,command,screenshot,delay}) {
  await command('Emulation.setDeviceMetricsOverride',{width:375,height:844,deviceScaleFactor:1,mobile:true});
  await evaluate(`(()=>{Game.pause();Game.reset(71);const ms=[Game.rollMonster('dewslime'),Game.rollMonster('dewslime')],a=Game.rollAccessory('epic'),d=JSON.parse(Game.save());d.state.roster.push(...ms);d.state.accessories.push(a);d.state.gold=1000;d.state.coins=40;d.state.materials.enhanceStone=10;Game.load(JSON.stringify(d));UI.openSheet('monsters');})()`);
  await evaluate("document.getElementById('open-evolution').click()");
  assert.ok(await evaluate("!document.querySelector('[data-evolve=\"dewslime:1\"]').disabled"));
  await screenshot('m2-375-evolution-table');
  await evaluate("document.querySelector('[data-evolve=\"dewslime:1\"]').click()");
  assert.ok(await evaluate("document.getElementById('evolution-reveal').open && !document.getElementById('evolution-reveal').classList.contains('revealed')"));
  await screenshot('m2-375-evolution-sink');await delay(850);
  assert.ok(await evaluate("document.querySelector('.evolution-after').textContent.includes('Ⅱ') && getComputedStyle(document.querySelector('.evolution-after')).opacity==='1'"));
  await screenshot('m2-375-evolution-II');
  assert.ok(await evaluate("Game.validateSave(Game.save())"));
  await evaluate("document.getElementById('close-evolution').click();document.getElementById('evolution-back').click();document.querySelector('.evo-2[data-monster]').click()");
  const oldCP=await evaluate('Game.getCP()');
  await evaluate("document.getElementById('enhance-monster').click()");
  assert.equal(await evaluate("Game.getState().roster.find(m=>m.evo===2).enhance"),1);
  assert.ok(await evaluate('Game.getCP()')>oldCP);
  await evaluate("document.getElementById('choose-accessory').click()");
  const beforeEquip=await evaluate("document.querySelector('.accessory-cp').textContent");
  await evaluate("document.querySelector('[data-equip]').click()");
  const afterEquip=await evaluate("document.querySelector('.accessory-cp').textContent");assert.notEqual(afterEquip,beforeEquip);
  await screenshot('m2-375-accessory-equipped');
  await evaluate("document.querySelector('[data-lock]').click()");
  assert.ok(await evaluate("document.querySelector('[data-sell]').disabled"));
  await evaluate("document.querySelector('[data-reroll]').click()");assert.equal(await evaluate('Game.getState().coins'),20);
  await evaluate("document.getElementById('accessory-back').click();document.getElementById('sheet').scrollTop=0");
  await screenshot('m2-375-enhanced-detail');
  await evaluate(`(()=>{const ms=Array.from({length:7},()=>Game.rollMonster('lakebat','rare')),d=JSON.parse(Game.save());d.state.roster.push(...ms);d.state.dex.lakebat={seen:true,caught:true};Game.load(JSON.stringify(d));UI.openSheet('monsters');})()`);
  await evaluate("document.getElementById('release-duplicates').click()");
  assert.equal(await evaluate("Game.getState().roster.filter(m=>m.speciesId==='lakebat').length"),3);
  await screenshot('m2-375-released');
  assert.ok(await evaluate("document.documentElement.scrollWidth===375 && document.getElementById('sheet').scrollWidth<=375"));
  // Save through the public API with an injected clock, then reload at the real wall time.
  await evaluate("document.getElementById('close-sheet').click();(()=>{const now=Date.now;Date.now=()=>now()-3*3600000;Game.save();})()");
  await command('Page.reload');await delay(400);await evaluate('Game.pause()');
  assert.ok(await evaluate("document.getElementById('offline-report').open && Game.getState().pendingReport.elapsedMs>=3*3600000"));
  assert.equal(await evaluate("document.getElementById('harvest-report').textContent"),'자루를 푼다');
  assert.ok(await evaluate("Game.getState().pendingReport.materials.enhanceStone>0 && Game.getState().pendingReport.accessories.length>0 && Game.getState().pendingReport.monsters.length>0"));
  await screenshot('m2-375-sack-mist');
  await evaluate("document.getElementById('harvest-report').click()");await delay(500);
  assert.ok(await evaluate("document.getElementById('offline-report').classList.contains('show-materials') && !document.getElementById('offline-report').classList.contains('show-monsters')"));
  await delay(400);assert.ok(await evaluate("document.getElementById('offline-report').classList.contains('show-accessories') && !document.getElementById('offline-report').classList.contains('show-monsters')"));
  await delay(850);await screenshot('m2-375-sack-open');
  assert.ok(await evaluate("document.getElementById('offline-report').classList.contains('show-monsters') && document.getElementById('offline-report').scrollWidth<=375"));
  await evaluate("document.getElementById('harvest-report').click()");assert.equal(await evaluate('Game.getState().pendingReport'),null);
  // Skip path takes one open tap, one reveal tap, and one harvest tap.
  await evaluate("Game.catchUp(60000);document.getElementById('harvest-report').click();document.getElementById('harvest-report').click()");
  assert.ok(await evaluate("document.getElementById('offline-report').classList.contains('show-monsters') && Game.getState().pendingReport!==null"));
  await evaluate("document.getElementById('harvest-report').click()");
  assert.ok(await evaluate("Game.validateSave(Game.save()) && document.documentElement.scrollWidth===375"));
  console.log('PASS M2 375px evolution sink/reveal, enhancement, visible CP '+beforeEquip+' -> '+afterEquip+', accessory lock/reroll, release, 3h sack/reveal/skip and no overflow');
};
