"use strict";
// Optional packaging helper, not a runtime build: regenerate after adding shell scripts/assets.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'), html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const monsters=JSON.parse(fs.readFileSync(path.join(root,'assets/monsters/manifest.json'),'utf8'));
const bosses=JSON.parse(fs.readFileSync(path.join(root,'assets/bosses/manifest.json'),'utf8'));
const paths=['./','index.html','style.css','manifest.webmanifest','sw.js','sw-shell.js',
  ...[...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),
  'assets/monsters/manifest.json','assets/bosses/manifest.json',...Object.values(monsters).flatMap(Object.values),...Object.values(bosses),
  ...['campfire','pen','workshop','altar','storehouse','garden','ground'].map(n=>'assets/camp/'+n+'.png'),
  ...['tamer_side','tamer_capture','fox_companion'].map(n=>'concepts/character/'+n+'.png'),
  'assets/pwa/icon-192.png','assets/pwa/icon-512.png'];
const unique=[...new Set(paths)];
for(const p of unique)if(!fs.existsSync(path.join(root,p)))throw new Error('Missing shell asset: '+p);
fs.writeFileSync(path.join(root,'sw-shell.js'),'"use strict";\n// Generated by scripts/pwa-shell.js. All URLs resolve within the app scope.\nself.APP_SHELL = '+JSON.stringify(unique,null,2)+';\n');
console.log('Offline shell: '+unique.length+' URLs');
